services:
  - docker
dist: focal
env:
global:
  - TZ=UTC
  - IMAGE_NAME="danysk/lss-pluto"

before_script:
  - export TAG="$(git describe || git log -n1 --date=format:'%Y-%m-%dT%H%M%S' --format=%cd)$(date +%Y-%m-%d_%H%M)

script:
  - docker build . -t $IMAGE_NAME:latest -t $IMAGE_NAME:$TAG .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin docker.io
  - docker push $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME:latest